// Groq uses the OpenAI-compatible API — llama-3.3-70b-versatile is free with 14,400 req/day
const BASE  = 'https://api.groq.com/openai/v1/chat/completions'
const MODEL = 'llama-3.3-70b-versatile'

const PROMPTS = {
  daily: (label, sections) => `You are a professional who writes their own daily work notes in a genuine, human voice.
For each date below, write a short paragraph (2 to 3 sentences) describing what was done that day.

Rules you must follow:
- Write in first person, past tense, as if the person wrote it themselves ("I worked on...", "I spent time...", "I had a productive session...")
- Sound natural and conversational, not robotic or corporate
- Vary your sentence structure so each day reads differently
- Do not use bullet points, dashes, asterisks, hyphens, or any list symbols anywhere in the text
- Do not copy or repeat the Jira issue titles word for word — rephrase them in your own words
- Keep it concise but warm and human

Return ONLY a valid JSON object with no extra text outside the JSON, where each key is a date string and each value is the paragraph for that day.

Work logs:
${sections}

Respond with ONLY the JSON object.`,

  weekly: (label, sections) => `You are a professional reflecting on their own week of work in a genuine, human voice.
For each week below, write a paragraph (3 to 4 sentences) capturing what was accomplished that week.

Rules you must follow:
- Write in first person, past tense, as if the person wrote it themselves
- Sound like a real person talking about their work, not a performance review
- Highlight what mattered most that week, not just a list of tasks
- Do not use bullet points, dashes, asterisks, hyphens, or any list symbols anywhere in the text
- Do not copy or repeat the Jira issue titles word for word — describe the work in your own words
- Each week should feel distinct, not templated

Return ONLY a valid JSON object with no extra text outside the JSON, where each key is the week start date and each value is the paragraph for that week.

Work logs:
${sections}

Respond with ONLY the JSON object.`,

  monthly: (label, lines) => `You are a professional writing a genuine end-of-month reflection on your own work.
Write one paragraph (4 to 5 sentences) that captures the bigger picture of what was achieved in ${label}.

Rules you must follow:
- Write in first person, past tense, as if the person wrote it themselves
- Sound thoughtful and reflective, not like a summary report generated by a machine
- Mention the themes and areas of focus, not a mechanical list of tasks
- Do not use bullet points, dashes, asterisks, hyphens, or any list symbols
- Do not plagiarise or copy the Jira issue titles directly — interpret the work and express it in your own human words
- The tone should feel like something a competent, thoughtful professional would actually write

Work logs:
${lines}

Respond with ONLY the paragraph text.`,
}

function parseJsonFromResponse(text) {
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim()
  return JSON.parse(cleaned)
}

async function callGroq(apiKey, prompt) {
  const res = await fetch(BASE, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.6,
      max_tokens: 4096,
    }),
  })

  if (!res.ok) {
    const err = await res.json()
    if (res.status === 401) throw new Error('Invalid Groq API key — check VITE_GROQ_KEY in your .env')
    if (res.status === 429) throw new Error('Groq rate limit reached — wait a moment and try again')
    throw new Error(err.error?.message || `Groq error ${res.status}`)
  }

  const data = await res.json()
  return data.choices?.[0]?.message?.content?.trim() ?? ''
}

export async function generateDailyReports(apiKey, byDate, monthLabel) {
  const sections = Object.entries(byDate)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, entries]) => {
      const lines = entries
        .map((e) => `  - [${e.issueKey}] ${e.issueSummary}: ${e.comment || '(no comment)'}`)
        .join('\n')
      return `${date}:\n${lines}`
    })
    .join('\n\n')

  const text = await callGroq(apiKey, PROMPTS.daily(monthLabel, sections))
  return parseJsonFromResponse(text)
}

export async function generateWeeklyReports(apiKey, byWeek, monthLabel) {
  const sections = byWeek
    .map(({ label, startDate, entries }) => {
      const lines = entries
        .map((e) => `  - [${e.issueKey}] ${e.issueSummary}: ${e.comment || '(no comment)'}`)
        .join('\n')
      return `Week starting ${startDate} (${label}):\n${lines}`
    })
    .join('\n\n')

  const text = await callGroq(apiKey, PROMPTS.weekly(monthLabel, sections))
  return parseJsonFromResponse(text)
}

export async function generateMonthlyReport(apiKey, worklogs, monthLabel) {
  const lines = worklogs
    .map((e) => `- [${e.issueKey}] ${e.issueSummary}: ${e.comment || '(no comment)'}`)
    .join('\n')

  return callGroq(apiKey, PROMPTS.monthly(monthLabel, lines))
}
